apiVersion: apps/v1
kind: Deployment
metadata:
  name: dootask-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dootask-php
  template:
    metadata:
      labels:
        app: dootask-php
    spec:
      initContainers:
      - name: wait-for-job
        image: busybox
        command: ['sh', '-c', 'until [ -f /app/success ]; do echo "waiting for init-job to complete"; sleep 2; done']
      containers:
      - name: php
        image: kuaifan/php:swoole-8.0.rc18
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: dootask-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: dootask-config
              key: DB_PORT
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: dootask-config
              key: DB_DATABASE
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: dootask-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dootask-secret
              key: DB_PASSWORD
        volumeMounts:
        - name: app-data
          mountPath: /var/www
          subPath: www
        - name: app-data
          mountPath: /etc/supervisor/conf.d
          subPath: supervisor/conf.d
        - name: app-data
          mountPath: /var/log/supervisor
          subPath: supervisor/log
        - name: app-data
          mountPath: /usr/local/etc/php/php.ini
          subPath: php/php.ini
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: dootask-app-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dootask-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dootask-nginx
  template:
    metadata:
      labels:
        app: dootask-nginx
    spec:
      initContainers:
      - name: wait-for-job
        image: busybox
        command: ['sh', '-c', 'until [ -f /app/success ]; do echo "waiting for init-job to complete"; sleep 2; done']
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 8088
          name: http
        - containerPort: 5443
          name: https
        volumeMounts:
        - name: app-data
          mountPath: /etc/nginx/conf.d
          subPath: nginx/conf.d
        - name: app-data
          mountPath: /var/www/public
          subPath: www/public
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: dootask-app-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: dootask-nginx
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8088
    name: http
  - port: 443
    targetPort: 5443
    name: https
  selector:
    app: dootask-nginx
