apiVersion: v1
kind: ConfigMap
metadata:
  name: dootask-config
data:
  DB_HOST: "dootask-mariadb"
  DB_PORT: "3306"
  DB_DATABASE: "dootask"
  DB_PREFIX: "pre_"
  REDIS_HOST: "dootask-redis"
  REDIS_PORT: "6379"
  TIMEZONE: "PRC"
---
apiVersion: v1
kind: Secret
metadata:
  name: dootask-secret
type: Opaque
stringData:
  DB_USERNAME: "dootask"
  DB_PASSWORD: "123456"
  DB_ROOT_PASSWORD: "7112d618a755dc5df42058226f1670e9db90"
  APP_KEY: "base64:8jegjH+F2Q1eBuvruKLaIs95L/DbqhlUDo62ckj/+s8="
---
