apiVersion: v1
kind: ConfigMap
metadata:
  name: dootask-config
data:
  DB_HOST: "dootask-mariadb"
  DB_PORT: "3306"
  DB_DATABASE: "dootask"
  REDIS_HOST: "dootask-redis"
  REDIS_PORT: "6379"
  TIMEZONE: "UTC"
---
apiVersion: v1
kind: Secret
metadata:
  name: dootask-secret
type: Opaque
stringData:
  DB_USERNAME: "dootask"
  DB_PASSWORD: "123456"
  DB_ROOT_PASSWORD: "123456"
  APP_KEY: "zzzzzz"
---

