apiVersion: v1
kind: ConfigMap
metadata:
  name: dootask-config
data:
  DB_HOST: "dootask-mariadb"
  DB_PORT: "3306"
  DB_DATABASE: "dootask"
  REDIS_HOST: "dootask-redis"
  REDIS_PORT: "6379"
  TIMEZONE: "PRC"
---
apiVersion: v1
kind: Secret
metadata:
  name: dootask-secret
type: Opaque
stringData:
  DB_USERNAME: "dootask"
  DB_PASSWORD: "your-password-here"
  DB_ROOT_PASSWORD: "your-root-password-here"
  APP_KEY: "your-app-key-here"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dootask-app-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
