apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dootask-mariadb
spec:
  serviceName: dootask-mariadb
  replicas: 1
  selector:
    matchLabels:
      app: dootask-mariadb
  template:
    metadata:
      labels:
        app: dootask-mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.7.3
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dootask-secret
              key: DB_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: dootask-config
              key: DB_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: dootask-secret
              key: DB_USERNAME
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dootask-secret
              key: DB_PASSWORD
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: mysql-conf
          mountPath: /etc/mysql/conf.d
          subPath: mysql/conf.d
        - name: mysql-script
          mountPath: /etc/mysql/repassword.sh
          subPath: mysql/repassword.sh
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: dootask-mysql-data-pvc
      - name: mysql-conf
        persistentVolumeClaim:
          claimName: dootask-app-pvc
      - name: mysql-script
        persistentVolumeClaim:
          claimName: dootask-app-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: dootask-mariadb
spec:
  ports:
  - port: 3306
  selector:
    app: dootask-mariadb
